#pragma once

#include "param_defs.h"

//=============================================================================
// Board-specific parameters
// These macros expand to lists of parameters for each type of function
// Modify as needed for each board
//=============================================================================

// Outputs (8)
#define ALL_OUTPUT_PARAMS \
    OUTPUT_PARAMS(0), OUTPUT_PARAMS(1), OUTPUT_PARAMS(2), OUTPUT_PARAMS(3), \
    OUTPUT_PARAMS(4), OUTPUT_PARAMS(5), OUTPUT_PARAMS(6), OUTPUT_PARAMS(7)

// Digital Inputs (2)
#define ALL_DIGITAL_INPUT_PARAMS \
    DIGITAL_INPUT_PARAMS(0), DIGITAL_INPUT_PARAMS(1)

// CAN Inputs (32)
#define ALL_CAN_INPUT_PARAMS \
    CAN_INPUT_PARAMS(0),  CAN_INPUT_PARAMS(1),  CAN_INPUT_PARAMS(2),  CAN_INPUT_PARAMS(3),  \
    CAN_INPUT_PARAMS(4),  CAN_INPUT_PARAMS(5),  CAN_INPUT_PARAMS(6),  CAN_INPUT_PARAMS(7),  \
    CAN_INPUT_PARAMS(8),  CAN_INPUT_PARAMS(9),  CAN_INPUT_PARAMS(10), CAN_INPUT_PARAMS(11), \
    CAN_INPUT_PARAMS(12), CAN_INPUT_PARAMS(13), CAN_INPUT_PARAMS(14), CAN_INPUT_PARAMS(15), \
    CAN_INPUT_PARAMS(16), CAN_INPUT_PARAMS(17), CAN_INPUT_PARAMS(18), CAN_INPUT_PARAMS(19), \
    CAN_INPUT_PARAMS(20), CAN_INPUT_PARAMS(21), CAN_INPUT_PARAMS(22), CAN_INPUT_PARAMS(23), \
    CAN_INPUT_PARAMS(24), CAN_INPUT_PARAMS(25), CAN_INPUT_PARAMS(26), CAN_INPUT_PARAMS(27), \
    CAN_INPUT_PARAMS(28), CAN_INPUT_PARAMS(29), CAN_INPUT_PARAMS(30), CAN_INPUT_PARAMS(31)

// CAN Outputs (32)
#define ALL_CAN_OUTPUT_PARAMS \
    CAN_OUTPUT_PARAMS(0),  CAN_OUTPUT_PARAMS(1),  CAN_OUTPUT_PARAMS(2),  CAN_OUTPUT_PARAMS(3),  \
    CAN_OUTPUT_PARAMS(4),  CAN_OUTPUT_PARAMS(5),  CAN_OUTPUT_PARAMS(6),  CAN_OUTPUT_PARAMS(7),  \
    CAN_OUTPUT_PARAMS(8),  CAN_OUTPUT_PARAMS(9),  CAN_OUTPUT_PARAMS(10), CAN_OUTPUT_PARAMS(11), \
    CAN_OUTPUT_PARAMS(12), CAN_OUTPUT_PARAMS(13), CAN_OUTPUT_PARAMS(14), CAN_OUTPUT_PARAMS(15), \
    CAN_OUTPUT_PARAMS(16), CAN_OUTPUT_PARAMS(17), CAN_OUTPUT_PARAMS(18), CAN_OUTPUT_PARAMS(19), \
    CAN_OUTPUT_PARAMS(20), CAN_OUTPUT_PARAMS(21), CAN_OUTPUT_PARAMS(22), CAN_OUTPUT_PARAMS(23), \
    CAN_OUTPUT_PARAMS(24), CAN_OUTPUT_PARAMS(25), CAN_OUTPUT_PARAMS(26), CAN_OUTPUT_PARAMS(27), \
    CAN_OUTPUT_PARAMS(28), CAN_OUTPUT_PARAMS(29), CAN_OUTPUT_PARAMS(30), CAN_OUTPUT_PARAMS(31)

// Virtual Inputs (16)
#define ALL_VIRTUAL_INPUT_PARAMS \
    VIRTUAL_INPUT_PARAMS(0),  VIRTUAL_INPUT_PARAMS(1),  VIRTUAL_INPUT_PARAMS(2),  VIRTUAL_INPUT_PARAMS(3),  \
    VIRTUAL_INPUT_PARAMS(4),  VIRTUAL_INPUT_PARAMS(5),  VIRTUAL_INPUT_PARAMS(6),  VIRTUAL_INPUT_PARAMS(7),  \
    VIRTUAL_INPUT_PARAMS(8),  VIRTUAL_INPUT_PARAMS(9),  VIRTUAL_INPUT_PARAMS(10), VIRTUAL_INPUT_PARAMS(11), \
    VIRTUAL_INPUT_PARAMS(12), VIRTUAL_INPUT_PARAMS(13), VIRTUAL_INPUT_PARAMS(14), VIRTUAL_INPUT_PARAMS(15)

// Conditions (32)
#define ALL_CONDITION_PARAMS \
    CONDITION_PARAMS(0),  CONDITION_PARAMS(1),  CONDITION_PARAMS(2),  CONDITION_PARAMS(3),  \
    CONDITION_PARAMS(4),  CONDITION_PARAMS(5),  CONDITION_PARAMS(6),  CONDITION_PARAMS(7),  \
    CONDITION_PARAMS(8),  CONDITION_PARAMS(9),  CONDITION_PARAMS(10), CONDITION_PARAMS(11), \
    CONDITION_PARAMS(12), CONDITION_PARAMS(13), CONDITION_PARAMS(14), CONDITION_PARAMS(15), \
    CONDITION_PARAMS(16), CONDITION_PARAMS(17), CONDITION_PARAMS(18), CONDITION_PARAMS(19), \
    CONDITION_PARAMS(20), CONDITION_PARAMS(21), CONDITION_PARAMS(22), CONDITION_PARAMS(23), \
    CONDITION_PARAMS(24), CONDITION_PARAMS(25), CONDITION_PARAMS(26), CONDITION_PARAMS(27), \
    CONDITION_PARAMS(28), CONDITION_PARAMS(29), CONDITION_PARAMS(30), CONDITION_PARAMS(31)

// Counters (4)
#define ALL_COUNTER_PARAMS \
    COUNTER_PARAMS(0), COUNTER_PARAMS(1), COUNTER_PARAMS(2), COUNTER_PARAMS(3)

// Flashers (4)
#define ALL_FLASHER_PARAMS \
    FLASHER_PARAMS(0), FLASHER_PARAMS(1), FLASHER_PARAMS(2), FLASHER_PARAMS(3)

// Starter disable outputs (8)
#define ALL_STARTER_DISABLE_PARAMS \
    STARTER_DISABLE_PARAM(0), STARTER_DISABLE_PARAM(1), STARTER_DISABLE_PARAM(2), STARTER_DISABLE_PARAM(3), \
    STARTER_DISABLE_PARAM(4), STARTER_DISABLE_PARAM(5), STARTER_DISABLE_PARAM(6), STARTER_DISABLE_PARAM(7)

// Keypads (2)
#define ALL_KEYPAD_PARAMS \
    KEYPAD_BASE_PARAMS(0), KEYPAD_BASE_PARAMS(1)

// Keypad 0 Buttons (20)
#define ALL_KEYPAD_0_BUTTON_PARAMS \
    KEYPAD_BUTTON_PARAMS(0, 0),  KEYPAD_BUTTON_PARAMS(0, 1),  KEYPAD_BUTTON_PARAMS(0, 2),  KEYPAD_BUTTON_PARAMS(0, 3),  \
    KEYPAD_BUTTON_PARAMS(0, 4),  KEYPAD_BUTTON_PARAMS(0, 5),  KEYPAD_BUTTON_PARAMS(0, 6),  KEYPAD_BUTTON_PARAMS(0, 7),  \
    KEYPAD_BUTTON_PARAMS(0, 8),  KEYPAD_BUTTON_PARAMS(0, 9),  KEYPAD_BUTTON_PARAMS(0, 10), KEYPAD_BUTTON_PARAMS(0, 11), \
    KEYPAD_BUTTON_PARAMS(0, 12), KEYPAD_BUTTON_PARAMS(0, 13), KEYPAD_BUTTON_PARAMS(0, 14), KEYPAD_BUTTON_PARAMS(0, 15), \
    KEYPAD_BUTTON_PARAMS(0, 16), KEYPAD_BUTTON_PARAMS(0, 17), KEYPAD_BUTTON_PARAMS(0, 18), KEYPAD_BUTTON_PARAMS(0, 19)

// Keypad 1 Buttons (20)
#define ALL_KEYPAD_1_BUTTON_PARAMS \
    KEYPAD_BUTTON_PARAMS(1, 0),  KEYPAD_BUTTON_PARAMS(1, 1),  KEYPAD_BUTTON_PARAMS(1, 2),  KEYPAD_BUTTON_PARAMS(1, 3),  \
    KEYPAD_BUTTON_PARAMS(1, 4),  KEYPAD_BUTTON_PARAMS(1, 5),  KEYPAD_BUTTON_PARAMS(1, 6),  KEYPAD_BUTTON_PARAMS(1, 7),  \
    KEYPAD_BUTTON_PARAMS(1, 8),  KEYPAD_BUTTON_PARAMS(1, 9),  KEYPAD_BUTTON_PARAMS(1, 10), KEYPAD_BUTTON_PARAMS(1, 11), \
    KEYPAD_BUTTON_PARAMS(1, 12), KEYPAD_BUTTON_PARAMS(1, 13), KEYPAD_BUTTON_PARAMS(1, 14), KEYPAD_BUTTON_PARAMS(1, 15), \
    KEYPAD_BUTTON_PARAMS(1, 16), KEYPAD_BUTTON_PARAMS(1, 17), KEYPAD_BUTTON_PARAMS(1, 18), KEYPAD_BUTTON_PARAMS(1, 19)

// All Keypad Button Params
#define ALL_KEYPAD_BUTTON_PARAMS \
    ALL_KEYPAD_0_BUTTON_PARAMS, \
    ALL_KEYPAD_1_BUTTON_PARAMS

// Keypad 0 Dials (2)
#define ALL_KEYPAD_0_DIAL_PARAMS \
    KEYPAD_DIAL_PARAMS(0, 0), KEYPAD_DIAL_PARAMS(0, 1)

// Keypad 1 Dials (2)
#define ALL_KEYPAD_1_DIAL_PARAMS \
    KEYPAD_DIAL_PARAMS(1, 0), KEYPAD_DIAL_PARAMS(1, 1)

// All Keypad Dial Params
#define ALL_KEYPAD_DIAL_PARAMS \
    ALL_KEYPAD_0_DIAL_PARAMS, \
    ALL_KEYPAD_1_DIAL_PARAMS
