#pragma once

#include "param_defs.h"

//=============================================================================
// Board-specific parameters
// These macros expand to lists of parameters for each type of function
// Modify as needed for each board
//=============================================================================

// Digital Inputs (8)
#define ALL_DIGITAL_INPUT_PARAMS \
    DIGITAL_INPUT_PARAMS(0), DIGITAL_INPUT_PARAMS(1), DIGITAL_INPUT_PARAMS(2), DIGITAL_INPUT_PARAMS(3), \
    DIGITAL_INPUT_PARAMS(4), DIGITAL_INPUT_PARAMS(5), DIGITAL_INPUT_PARAMS(6), DIGITAL_INPUT_PARAMS(7)

// Digital Outputs (4)
#define ALL_DIGITAL_OUTPUT_PARAMS \
    DIGITAL_OUTPUT_PARAMS(0), DIGITAL_OUTPUT_PARAMS(1), DIGITAL_OUTPUT_PARAMS(2), DIGITAL_OUTPUT_PARAMS(3)

// Analog Inputs (5)
#define ALL_ANALOG_INPUT_PARAMS \
    ANALOG_INPUT_PARAMS(0), ANALOG_INPUT_PARAMS(1), ANALOG_INPUT_PARAMS(2), ANALOG_INPUT_PARAMS(3), ANALOG_INPUT_PARAMS(4)

// CAN Inputs (32)
#define ALL_CAN_INPUT_PARAMS \
    CAN_INPUT_PARAMS(0),  CAN_INPUT_PARAMS(1),  CAN_INPUT_PARAMS(2),  CAN_INPUT_PARAMS(3),  \
    CAN_INPUT_PARAMS(4),  CAN_INPUT_PARAMS(5),  CAN_INPUT_PARAMS(6),  CAN_INPUT_PARAMS(7)

// CAN Outputs (32)
#define ALL_CAN_OUTPUT_PARAMS \
    CAN_OUTPUT_PARAMS(0),  CAN_OUTPUT_PARAMS(1),  CAN_OUTPUT_PARAMS(2),  CAN_OUTPUT_PARAMS(3),  \
    CAN_OUTPUT_PARAMS(4),  CAN_OUTPUT_PARAMS(5),  CAN_OUTPUT_PARAMS(6),  CAN_OUTPUT_PARAMS(7)

// Virtual Inputs (16)
#define ALL_VIRTUAL_INPUT_PARAMS \
    VIRTUAL_INPUT_PARAMS(0),  VIRTUAL_INPUT_PARAMS(1),  VIRTUAL_INPUT_PARAMS(2),  VIRTUAL_INPUT_PARAMS(3),  \
    VIRTUAL_INPUT_PARAMS(4),  VIRTUAL_INPUT_PARAMS(5),  VIRTUAL_INPUT_PARAMS(6),  VIRTUAL_INPUT_PARAMS(7)

// Conditions (32)
#define ALL_CONDITION_PARAMS \
    CONDITION_PARAMS(0),  CONDITION_PARAMS(1),  CONDITION_PARAMS(2),  CONDITION_PARAMS(3),  \
    CONDITION_PARAMS(4),  CONDITION_PARAMS(5),  CONDITION_PARAMS(6),  CONDITION_PARAMS(7)

// Counters (4)
#define ALL_COUNTER_PARAMS \
    COUNTER_PARAMS(0), COUNTER_PARAMS(1), COUNTER_PARAMS(2), COUNTER_PARAMS(3)

// Flashers (4)
#define ALL_FLASHER_PARAMS \
    FLASHER_PARAMS(0), FLASHER_PARAMS(1), FLASHER_PARAMS(2), FLASHER_PARAMS(3)
